[package]
name = "xmp-batch"
version = "0.1.0"
authors = ["Tim DuBois <tim@neophilus.net>"]
edition = "2018"

[dependencies]
failure = "0.1"
rexiv2 = "0.7"
serde_yaml = "0.8"
serde = "1.0"
serde_derive = "1.0"
url = "1.7"
url_serde = "0.2"
globwalk = "0.7"
